name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build EXE
        run: |
          npm install -g pkg
          pkg main.js --targets node18-win-x64 --output AmazonOptimizer.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AmazonOptimizer
          path: AmazonOptimizer.exe
